# Generated by Django 3.1.3 on 2022-06-11 10:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210306_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='profile_pictures'),
            preserve_default=False,
        ),
    ]
